name: Docker Image CI

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      gdl-v:
        description: 'Version of gallery-dl'
        required: true
        default: 'v1.19.0'
      ytdlp-v:
        description: 'Verion of yt-dlp'
        required: true
        default: '2021.09.25'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: aphy7/gallery-dl:latest aphy7/gallery-dl:${{ github.event.inputs.gdl-v }}-${{ github.event.inputs.ytdlp-v }}
          platforms: linux/amd64
